apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: backend
  namespace: promhub
spec:
  domains:
    - api.promhub.io
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: frontend
  namespace: promhub
spec:
  domains:
    - promhub.io
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: backend
  namespace: promhub
  annotations:
    networking.gke.io/managed-certificates: backend
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: backend
          servicePort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: frontend
  namespace: promhub
  annotations:
    networking.gke.io/managed-certificates: frontend
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 3000
