version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:11.7
    restart: always
    environment:
      POSTGRES_DB: promhub
      POSTGRES_USER: "promhub"
      POSTGRES_PASSWORD: "pass"
    ports:
      - 5432:5432
  dbimport:
    container_name: dbimport
    image: gcr.io/mateo-burillo-ns/promcat-dbimport:staging
    restart: on-failure
    environment:
      DATABASE_URL: "postgres://promhub:pass@postgres/promhub?sslmode=disable"
      RESOURCES_PATH: "/resources/resources"
      APPS_PATH: "/resources/apps"
    command:  ["/bin/sh", "-c", "sleep 10 && /bin/dbimport && touch /resources/file.unlock"]
    volumes:
      - resources:/resources
    depends_on:
      - postgres
      - resources
  resources:
    container_name: resources
    image: gcr.io/mateo-burillo-ns/promcat-resources:staging
    command: ["/bin/sh", "-c", "cp -r /resources/* /shared-resources && /bin/sh /wait/wait.sh"]
    volumes:
      - resources:/shared-resources
      - ./wait.sh:/wait/wait.sh
  backend:
    container_name: backend
    image: gcr.io/mateo-burillo-ns/promcat-backend:staging
    environment:
      DATABASE_URL: "postgres://promhub:pass@postgres/promhub?sslmode=disable"
    ports:
      - 8080:8080
  frontend:
    container_name: frontend
    image: gcr.io/mateo-burillo-ns/promcat-frontend:staging
    ports:
      - 3000:3000
    environment:
      BASE_URL: "http://frontend:3000"
      API_URL: "http://backend:8080"
volumes:
  resources: